### ISSUE TITLE
Get both Depth and Color at the same time?

### ISSUE THREAD

**Issue by stanleyshly** [CountingShe3p/py-kinect-toolbox#1]
Is it possible to get both Raw Depth and Raw Color at the same time, and what is the delay if I call the get function for color, then the depth in sequentially?Also, if I save both the Raw Depth and Raw Color as png or tiff using OpenCV, can I apply standard Kinect intrinsic when processing later? I greatly appreciate your library, and thank you for your time!

**Comment by nikwl** [comment]
Hi!

Using the `get_frame` function you can request both the raw color and raw depth images simultaneously by passing an iterable of frame types:
```python
color_frame, depth_frame = k.get_frame([ktb.RAW_COLOR, ktb.RAW_DEPTH])
```

You should also be able to undistort and register the saved depth and color images after the fact:
```python
import numpy as np
import ktb

k = ktb.Kinect()
color_frame, depth_frame = k.get_frame([ktb.RAW_COLOR, ktb.RAW_DEPTH])

undistorted, registered = k._new_frame((int(512), int(424), int(4))), k._new_frame((int(512), int(424), int(4)))
k.registration.undistortDepth(depth_frame , undistorted)
k.registration.apply(color_frame, depth_frame , undistorted, registered)
undistorted_depth = np.copy(undistorted.asarray(np.float32))
registered_color = np.copy(registered.asarray(np.uint8))[...,:3]
```

I didn't write a method for this so the above code references some private methods. I'm also not able to test the code right now because I don't have access to a kinect so let me know if this throws any exceptions. 

Hope this helps!

**Comment by stanleyshly** [comment]
Thank you for your response! However, does you code distort for Kinect v1 or Kinect v2, or both? Also, since Open3d's reconstruction system wants raw images, should I apply the undistort and then use default Kinect intrinsics, or should I just use cv2.imwrite and save to a 16bit png or tiff without undistorting? And also, do I only need to undistort the depth, or do I need to undistort the color too?

**Comment by nikwl** [comment]
This library has only been tested with the Kinectv2 and I believe that the underlying library, pylibfreenect2, only has support for the Kinectv2.

I think I'm a little confused as to exactly what type of image you're looking for. If you need of the raw color and raw depth images as input for another system then you can return those directly using the method above. If you'd also like the undistorted and registered depth and color images (to display live video, for instance) you could get those too:
```python
raw_color_frame, raw_depth_frame, color_frame, depth_frame = k.get_frame([ktb.RAW_COLOR, ktb.RAW_DEPTH, ktb.COLOR, ktb.DEPTH])
```
Look at the [table of frame types](https://github.com/nikwl/kinect-toolbox#methods) in the readme for a list of the types of images that the kinect can return.

**Comment by stanleyshly** [comment]
Thank you for your help.
