### ISSUE TITLE
Infrared image cannot be displayed normally ?

### ISSUE THREAD

**Issue by WangXingfang** [CountingShe3p/py-kinect-toolbox#2]
After using "get_frame(ktb.IR)" to obtain a IR frame, the IR frame cannot displayed normally by opencv2.imshow(). The frame is all white.

**Comment by WangXingfang** [comment]
The range of IR frame data is from 0.0 to 65535.0.

**Comment by WangXingfang** [comment]
ir_frame = ir_frame.astype(np.uint16)

**Comment by nikwl** [comment]
The ir frame may be out of the visible range, I can't remember if that's the default format that it returns. Either that or your kinect isn't working correctly. 

If the values are just out of the visible range then you can rescale it with this function. 
```
import numpy as np
from matplotlib import cm

def colorize_image(img, cmap="gray", vmin=None, vmax=None):
    assert len(img.shape) < 3

    # Get the min and max
    if vmin is None:
        vmin = img.min()
    if vmax is None:
        vmax = img.max()

    # Clip and rescale
    img = np.clip((img - vmin) / (vmax - vmin), 0.0, 1.0)

    if cmap is None or cmap == "None":
        return (np.dstack((img, img, img, np.ones((img.shape)))) * 255).astype(np.uint8)

    if cmap == "fire":
        cmap = fire
    else:
        cmap = cm.get_cmap(cmap)

    # Apply the colormap
    return (cmap(img) * 255).astype(np.uint8)
```
